apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: example
spec:
  projectID: crossplane-playground
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: gcp-creds
      key: creds
