apiVersion: app.uppound.io/v1alpha1
kind: XApp
metadata:
  name: example
spec:
  compositionSelector:
    matchLabels:
      language: kcl
  parameters:
    id: uppound-gcp
    containers:
      - name: frontend
        image: tr0njavolta/uppound-demo-frontend:latest
      - name: backend
        image: tr0njavolta/uppound-demo-backend:latest
    region: us-west1
    version: "1.30"
    nodes:
      count: 3
      instanceType: e2-standard-2
  writeConnectionSecretToRef:
    name: uppound-gcp-kubeconfig
    namespace: default
